import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Widget from "@/components/Widget/Widget";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={styles["main__container"]}>
      <Head>
        <title>Widget Testing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Widget />
    </div>
  );
}
